name: Feature Request
description: Suggest an idea for aitap
title: '[FEATURE] '
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.

  - type: checkboxes
    id: checks
    attributes:
      label: Before submitting
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the [Contributing Guide](../CONTRIBUTING.md)
          required: false

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: |
        I'm always frustrated when...
        Or: It would be easier if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
      placeholder: Describe alternative approaches...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the project does this relate to?
      options:
        - P2P / Direct Line
        - Relay Server
        - Meeting Point
        - CLI / User Interface
        - Protocol / Messaging
        - Security
        - Performance
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be valuable
      placeholder: |
        Example: As a user running multiple AI agents, I want...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here
      placeholder: Any additional information, ideas, or references...

  - type: checkboxes
    id: willing
    attributes:
      label: Would you like to work on this?
      description: Would you be interested in submitting a PR to implement this feature?
      options:
        - label: Yes, I'd like to implement this feature
          required: false
        - label: I might need help getting started
          required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - 'Nice to have'
        - 'Would make things easier'
        - 'Critical for my use case'
      default: 1
